[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "backend"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

# This handles the Python environment for Netlify
[functions."main"]
  runtime = "python"
